FROM openjdk:17-jdk-slim

WORKDIR /app

COPY gradlew /app/gradlew
COPY gradle /app/gradle
COPY app/build.gradle /app/build.gradle
COPY settings.gradle /app/settings.gradle

RUN chmod +x /app/gradlew

RUN ./gradlew build --no-daemon --stacktrace --info || return 0

COPY app/src /app/src

CMD ["./gradlew", "test"]
